services:
  - type: web
    name: aternos-guard
    env: node
    buildCommand: npm pkg delete scripts.postinstall || true && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
